[project]
name = 'stackpay'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.arch]
path = 'contracts/architecture.clar'
clarity_version = 4
epoch = '3.3'

[contracts.proc]
path = 'contracts/processor.clar'
clarity_version = 4
epoch = '3.3'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
